# Generated by Django 4.2.29 on 2026-03-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when the object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated every time the object is saved')),
                ('work_quality', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Quality of work produced (1-5)')),
                ('attitude', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Professional attitude and behavior (1-5)')),
                ('overall_rating', models.FloatField(help_text='Overall performance rating (1-5)')),
                ('recommendation', models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not Recommended'), ('highly_recommended', 'Highly Recommended')], help_text='Final recommendation', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional comments and observations')),
                ('student', models.ForeignKey(help_text='Student being evaluated', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Supervisor who gave this evaluation', limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
