# Generated by Django 4.2.29 on 2026-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Company name (for supervisors)', max_length=200),
        ),
    ]
