# Generated by Django 4.2.29 on 2026-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='required_hours',
            field=models.FloatField(help_text='Total hours required to complete OJT (must be specified)'),
        ),
    ]
