# Generated by Django 4.2.29 on 2026-03-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the DTR entry')),
                ('time_in', models.TimeField(help_text='Clock-in time')),
                ('time_out', models.TimeField(blank=True, help_text='Clock-out time (can be logged later)', null=True)),
                ('selfie', models.ImageField(help_text='Selfie taken at clock-in for verification', upload_to='selfies/%Y/%m/')),
                ('hours_rendered', models.FloatField(default=0, help_text='Hours worked (auto-calculated from time_in and time_out)')),
                ('notes', models.TextField(blank=True, help_text="Optional notes about the day's activities")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student who logged this DTR', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='dtr_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DTR Log',
                'verbose_name_plural': 'DTR Logs',
                'ordering': ['-date', '-time_in'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
