# Generated by Django 4.2.29 on 2026-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0002_add_supervisor_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrlog',
            name='logout_selfie',
            field=models.ImageField(blank=True, help_text='Selfie taken at clock-out for verification', null=True, upload_to='selfies/%Y/%m/'),
        ),
    ]
