# Generated by Django 4.2.29 on 2026-03-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when the object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated every time the object is saved')),
                ('week_number', models.IntegerField(help_text='Week number of OJT (1, 2, 3, etc.)')),
                ('content', models.TextField(help_text='Journal content/reflection')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review status', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text="Teacher's feedback on the journal")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the journal was submitted')),
                ('student', models.ForeignKey(help_text='Student who submitted this journal', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
